// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_allele_freq_btwn_cpp
double get_allele_freq_btwn_cpp(arma::colvec alleles, arma::colvec locations, int allele, int location);
RcppExport SEXP _RPTfast_get_allele_freq_btwn_cpp(SEXP allelesSEXP, SEXP locationsSEXP, SEXP alleleSEXP, SEXP locationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type alleles(allelesSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< int >::type allele(alleleSEXP);
    Rcpp::traits::input_parameter< int >::type location(locationSEXP);
    rcpp_result_gen = Rcpp::wrap(get_allele_freq_btwn_cpp(alleles, locations, allele, location));
    return rcpp_result_gen;
END_RCPP
}
// get_allele_freq_within_cpp
double get_allele_freq_within_cpp(arma::colvec alleles, int allele);
RcppExport SEXP _RPTfast_get_allele_freq_within_cpp(SEXP allelesSEXP, SEXP alleleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type alleles(allelesSEXP);
    Rcpp::traits::input_parameter< int >::type allele(alleleSEXP);
    rcpp_result_gen = Rcpp::wrap(get_allele_freq_within_cpp(alleles, allele));
    return rcpp_result_gen;
END_RCPP
}
// get_facil_dist
arma::mat get_facil_dist(arma::colvec locs_unique, arma::mat fasta_sub_meta, arma::colvec sample_locs);
RcppExport SEXP _RPTfast_get_facil_dist(SEXP locs_uniqueSEXP, SEXP fasta_sub_metaSEXP, SEXP sample_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type locs_unique(locs_uniqueSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fasta_sub_meta(fasta_sub_metaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sample_locs(sample_locsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_facil_dist(locs_unique, fasta_sub_meta, sample_locs));
    return rcpp_result_gen;
END_RCPP
}
// get_facil_dist_fst
arma::mat get_facil_dist_fst(arma::colvec locs_unique, arma::mat fasta_sub_meta, arma::colvec sample_locs);
RcppExport SEXP _RPTfast_get_facil_dist_fst(SEXP locs_uniqueSEXP, SEXP fasta_sub_metaSEXP, SEXP sample_locsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type locs_unique(locs_uniqueSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fasta_sub_meta(fasta_sub_metaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sample_locs(sample_locsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_facil_dist_fst(locs_unique, fasta_sub_meta, sample_locs));
    return rcpp_result_gen;
END_RCPP
}
// make_ref_cpp
NumericVector make_ref_cpp(NumericMatrix fasta);
RcppExport SEXP _RPTfast_make_ref_cpp(SEXP fastaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fasta(fastaSEXP);
    rcpp_result_gen = Rcpp::wrap(make_ref_cpp(fasta));
    return rcpp_result_gen;
END_RCPP
}
// find_major_alleles_cpp
NumericVector find_major_alleles_cpp(NumericMatrix fasta, NumericVector ref);
RcppExport SEXP _RPTfast_find_major_alleles_cpp(SEXP fastaSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fasta(fastaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    rcpp_result_gen = Rcpp::wrap(find_major_alleles_cpp(fasta, ref));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RPTfast_get_allele_freq_btwn_cpp", (DL_FUNC) &_RPTfast_get_allele_freq_btwn_cpp, 4},
    {"_RPTfast_get_allele_freq_within_cpp", (DL_FUNC) &_RPTfast_get_allele_freq_within_cpp, 2},
    {"_RPTfast_get_facil_dist", (DL_FUNC) &_RPTfast_get_facil_dist, 3},
    {"_RPTfast_get_facil_dist_fst", (DL_FUNC) &_RPTfast_get_facil_dist_fst, 3},
    {"_RPTfast_make_ref_cpp", (DL_FUNC) &_RPTfast_make_ref_cpp, 1},
    {"_RPTfast_find_major_alleles_cpp", (DL_FUNC) &_RPTfast_find_major_alleles_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RPTfast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
