# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_allele_freq_btwn_cpp <- function(alleles, locations, allele, location) {
    .Call('_RPTfast_get_allele_freq_btwn_cpp', PACKAGE = 'RPTfast', alleles, locations, allele, location)
}

#' @export
get_allele_freq_within_cpp <- function(alleles, allele) {
    .Call('_RPTfast_get_allele_freq_within_cpp', PACKAGE = 'RPTfast', alleles, allele)
}

#' @export
get_facil_dist <- function(locs_unique, fasta_sub_meta, sample_locs) {
    .Call('_RPTfast_get_facil_dist', PACKAGE = 'RPTfast', locs_unique, fasta_sub_meta, sample_locs)
}

#' @export
get_facil_dist_fst <- function(locs_unique, fasta_sub_meta, sample_locs) {
    .Call('_RPTfast_get_facil_dist_fst', PACKAGE = 'RPTfast', locs_unique, fasta_sub_meta, sample_locs)
}

#' @export
make_ref_cpp <- function(fasta) {
    .Call('_RPTfast_make_ref_cpp', PACKAGE = 'RPTfast', fasta)
}

#' @export
find_major_alleles_cpp <- function(fasta, ref) {
    .Call('_RPTfast_find_major_alleles_cpp', PACKAGE = 'RPTfast', fasta, ref)
}

